version: '3.8'

# services:
#   connector:
#     build:
#       context: app
#     volumes:
#       - ./:/app
#     ports:
#       - '19191:19191'
#       - '19192:19192'
#       - '19193:19193'
#       - '19194:19194'
#       - '19195:19195'
#       - '19291:19291'
#     # command: ['sleep', '3600']
#     entrypoint:
#       [
#         'java',
#         '-Dedc.fs.config=/app/config.properties',
#         '-jar',
#         '/app/build/libs/connector.jar',
#       ]

services:
  connector:
    build:
      context: .
      dockerfile: app/dockerfile
    ports:
      - '19191:19191'
      - '19192:19192'
      - '19193:19193'
      - '19194:19194'
      - '19195:19195'
      - '19291:19291'
