version: '3.8'

services:
  connector:
    build:
      context: connector
    volumes:
      - ./:/connector
    ports:
      - '19191:19191'
      - '19192:19192'
      - '19193:19193'
      - '19194:19194'
      - '19195:19195'
      - '19291:19291'
    entrypoint:
      [
        'java',
        '-Dedc.fs.config=./config.properties',
        '-jar',
        '/app/connector.jar',
      ]
