# # ---------- Stage 1: Build the JAR ----------
# FROM eclipse-temurin:17-jdk AS builder

# WORKDIR /app

# # Copy build files
# # COPY ./app /app
# COPY . .

# # Give exec permissions to the Gradle wrapper
# RUN chmod +x ./gradlew

# # Build the shadow JAR
# RUN ./gradlew shadowJar

# # ---------- Stage 2: Runtime ----------
# FROM eclipse-temurin:17-jdk

# WORKDIR /app

# # Copy the JAR from the builder stage
# # COPY --from=builder /app/build/libs/connector.jar /app/connector.jar

# # Optional: copy OpenTelemetry agent if needed
# # COPY opentelemetry-javaagent.jar /app/opentelemetry-javaagent.jar

# # Default command will be set in docker-compose

# FROM openjdk:17-slim

# WORKDIR /app

# copy . .

# ---- Stage 1: Build JAR ----
FROM eclipse-temurin:17-jdk AS builder

WORKDIR /workspace

# Go up from app/, get the whole project
COPY ../.. .

RUN chmod +x ./gradlew
RUN ./gradlew :app:shadowJar

# ---- Stage 2: Runtime ----
FROM eclipse-temurin:17-jre

WORKDIR /app

COPY --from=builder /workspace/app/build/libs/connector.jar ./connector.jar
# COPY config.properties ./config.properties
COPY app/config.properties ./config.properties

ENTRYPOINT ["java", "-Dedc.fs.config=/app/config.properties", "-jar", "connector.jar"]
